# Generated by Django 3.2.7 on 2021-12-02 05:26

from django.db import migrations, models
import myResidence.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_scheme', models.TextField(blank=True, max_length=255, null=True)),
                ('isactive', models.TextField(blank=True, choices=[('True', 'True'), ('', 'False')], db_column='isActive', default='True', max_length=100, null=True)),
            ],
            options={
                'db_table': 'account_customize',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.TextField(max_length=100)),
                ('dateofbirth', models.DateField()),
                ('image', models.ImageField(blank=True, default='static/uploaded/profile/default.png', null=True, upload_to=myResidence.models.admin_upload)),
                ('isactive', models.TextField(blank=True, choices=[('True', 'True'), ('', 'False')], db_column='isActive', default='True', max_length=100, null=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnnouncementNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=myResidence.models.news_upload)),
                ('headline', models.TextField(max_length=255)),
                ('content', models.TextField()),
                ('datepublished', models.DateField()),
                ('isactive', models.TextField(blank=True, choices=[('True', 'True'), ('', 'False')], db_column='isActive', default='True', max_length=100, null=True)),
            ],
            options={
                'db_table': 'cms_news',
                'ordering': ['-datepublished'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttritionPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('attrition_probability', models.FloatField()),
                ('isactive', models.TextField(blank=True, choices=[('True', 'True'), ('', 'False')], db_column='isActive', default='True', max_length=100, null=True)),
            ],
            options={
                'db_table': 'tenant_attrition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('billing_fee', models.FloatField()),
                ('due_date', models.DateField()),
                ('status', models.TextField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], default='Pending', max_length=100)),
                ('is_late', models.TextField(max_length=100)),
                ('isactive', models.TextField(blank=True, choices=[('True', 'True'), ('', 'False')], db_column='isActive', default='True', max_length=100, null=True)),
            ],
            options={
                'db_table': 'billings',
                'ordering': ['-date_issued'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BillingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_code', models.TextField(max_length=50)),
                ('billing_name', models.TextField(max_length=100)),
                ('isactive', models.TextField(blank=True, choices=[('True', 'True'), ('', 'False')], db_column='isActive', default='True', max_length=100, null=True)),
            ],
            options={
                'db_table': 'billing_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('activity', models.TextField(max_length=100)),
                ('action', models.TextField(max_length=255)),
                ('isactive', models.TextField(blank=True, choices=[('True', 'True'), ('', 'False')], db_column='isActive', default='True', max_length=100, null=True)),
            ],
            options={
                'db_table': 'log_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('activity', models.TextField(max_length=100)),
                ('action', models.TextField(max_length=255)),
                ('isactive', models.TextField(blank=True, choices=[('True', 'True'), ('', 'False')], db_column='isActive', default='True', max_length=100, null=True)),
            ],
            options={
                'db_table': 'log_tenants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProofOfPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=myResidence.models.proof_upload)),
                ('status', models.TextField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=100)),
                ('isactive', models.TextField(blank=True, choices=[('True', 'True'), ('', 'False')], db_column='isActive', default='True', max_length=100, null=True)),
            ],
            options={
                'db_table': 'proof_payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('category', models.TextField(max_length=100)),
                ('details', models.TextField()),
                ('date_available', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=myResidence.models.repair_upload)),
                ('status', models.TextField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved'), ('Cancelled', 'Cancelled'), ('Date_Unavailable', 'Date Unavailable'), ('Scheduled', 'Scheduled')], default='Pending', max_length=255)),
                ('isactive', models.TextField(blank=True, choices=[('True', 'True'), ('', 'False')], db_column='isActive', default='True', max_length=100, null=True)),
            ],
            options={
                'db_table': 'repair',
                'ordering': ['-date_issued'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('category', models.TextField(max_length=100)),
                ('details', models.TextField()),
                ('neighbour', models.TextField(blank=True, max_length=100, null=True)),
                ('staff', models.TextField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=myResidence.models.report_upload)),
                ('status', models.TextField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=255)),
                ('isactive', models.TextField(blank=True, choices=[('True', 'True'), ('', 'False')], db_column='isActive', default='True', max_length=100, null=True)),
            ],
            options={
                'db_table': 'report',
                'ordering': ['-date_issued'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.TextField(max_length=100)),
                ('work_address', models.TextField(max_length=100)),
                ('dateofbirth', models.DateField()),
                ('image', models.ImageField(blank=True, default='static/uploaded/profile/default.png', null=True, upload_to=myResidence.models.tenant_upload)),
                ('isactive', models.TextField(blank=True, choices=[('True', 'True'), ('', 'False')], db_column='isActive', default='True', max_length=100, null=True)),
            ],
            options={
                'db_table': 'tenants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TenantAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_link', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=myResidence.models.ad_upload)),
                ('isactive', models.TextField(blank=True, choices=[('True', 'True'), ('', 'False')], db_column='isActive', default='True', max_length=100, null=True)),
            ],
            options={
                'db_table': 'cms_announcements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TenantContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_date', models.DateField(blank=True, null=True)),
                ('rent', models.FloatField()),
                ('late_collection', models.FloatField()),
                ('grace_period', models.IntegerField()),
                ('legal_rent', models.FloatField()),
                ('deposit', models.FloatField()),
                ('months_occupied', models.IntegerField()),
                ('roommates', models.IntegerField()),
                ('epay', models.IntegerField()),
                ('confirmation', models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'tenant_contract',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TenantRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=100)),
                ('password', models.TextField(max_length=100)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('first_name', models.TextField(max_length=100)),
                ('last_name', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=100)),
                ('contact', models.TextField(max_length=100)),
                ('work_address', models.TextField(blank=True, max_length=255, null=True)),
                ('dateofbirth', models.DateField()),
                ('image', models.ImageField(blank=True, default='static/uploaded/profile/default.png', null=True, upload_to=myResidence.models.reg_upload)),
                ('status', models.TextField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=100)),
                ('isactive', models.TextField(blank=True, choices=[('True', 'True'), ('', 'False')], db_column='isActive', default='True', max_length=100, null=True)),
            ],
            options={
                'db_table': 'tenant_registration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TenantUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('room', models.TextField(max_length=11)),
                ('tenant_num', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tenant_unit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TermsAndCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateField(auto_now_add=True)),
                ('tnc_content', models.TextField()),
            ],
            options={
                'db_table': 'cms_tnc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('purpose', models.TextField(max_length=100)),
                ('visitor_count', models.IntegerField()),
                ('visitor_names', models.TextField(max_length=255)),
                ('visit_date', models.DateField()),
                ('duration', models.TextField(max_length=100)),
                ('status', models.TextField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=100)),
                ('reason', models.TextField(max_length=255)),
                ('isactive', models.TextField(blank=True, choices=[('True', 'True'), ('', 'False')], db_column='isActive', default='True', max_length=100, null=True)),
            ],
            options={
                'db_table': 'visitors',
                'ordering': ['-date_issued'],
                'managed': False,
            },
        ),
    ]
