# Generated by Django 3.2.7 on 2021-12-08 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myResidence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myResidence.tenant'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myResidence.tenantunit'),
        ),
    ]
